# Generated by Django 4.1.7 on 2023-07-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delegate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Destination", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("branding", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={"verbose_name_plural": "delegates",},
        ),
        migrations.CreateModel(
            name="DelegateMeetingRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("delegates", models.ManyToManyField(to="delegate.delegate")),
            ],
        ),
    ]
