# Generated by Django 4.2.4 on 2023-09-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delegate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegatemeetingregister",
            name="day_of_participation",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
