# Generated by Django 5.0.6 on 2024-07-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegate', '0002_delegatemeetingregister_day_of_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegatemeetingregister',
            name='day_of_participation',
        ),
    ]
