# Generated by Django 5.1 on 2024-09-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegate', '0003_remove_delegatemeetingregister_day_of_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegatemeetingregister',
            name='day_of_participation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
