# Generated by Django 5.2 on 2025-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegate', '0004_delegatemeetingregister_day_of_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='solutions',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
