# Generated by Django 5.2 on 2025-04-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegate', '0005_delegate_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='solutions',
            field=models.CharField(max_length=500),
        ),
    ]
